from google import genai
from google.genai import types
import json
import os
from datetime import datetime
import time
import random
from config import GEMINI_API_KEY, LOGS_DIR
from topic_tracker import load_tracker, check_story_uniqueness, check_cooldowns
from ecosystem_logic import get_slot_info, get_category_prompt_enhancement

# ── PROMPT TEMPLATES (AGENTIC LOOP) ────────────────────────────────────────

SYSTEM_PERSONA = """Role: You are an expert AI Research Content Creator specialized in viral, high-retention YouTube Shorts.
Your goal is to convert complex engineering papers into "snackable" scripts that hit 1k+ views by maximizing "Swipe-to-Watch" ratios.
Tone: Highly opinionated, analytical, and critical. You are a "Tech Insider" who doesn't just read the news; you deconstruct it, challenge corporate narratives, and offer bold predictions.
Target Audience: USA-based tech professionals and engineers. You MUST use American English spelling, USD ($) for any currency, and US-centric tech analogies.
Constraint Checklist:
- No Fluff: Remove "In this video," "Hello everyone," or "Today we explore."
- NO INFOGRAPHICS: Do not include infographics, flowcharts, or slides in the script structure.
- VOCAL DYNAMICS: You MUST use heavy punctuation (commas, ellipses '...', exclamation marks, italics, ALL CAPS) around key technical terms and transitions. The TTS engine relies entirely on punctuation to vary pitch and emphasis.
- CLARITY OVER JARGON: Avoid jargon chains. If you use a complex term like 'Quantization', follow it immediately with a simple 3-word analogy (e.g., '...essentially data compression').
- PERSONAL STAKES: You MUST explain why the viewer should care about this technical change in their daily life, job security, or digital privacy.
- CRITICAL COMMENTARY (YPP COMPLIANCE): You MUST provide a unique, PERSONAL perspective that could NOT be generated by a generic AI. Do not just summarize facts. You must: (1) Take a bold, controversial stance on the news. (2) Predict specific consequences that aren't obvious. (3) Name specific winners and losers. (4) Reference your own past coverage or opinions for continuity. This is what separates 'human editorial' from 'AI summary' in YouTube's monetization review.
SUCCESS PATTERNS (2026): 
- HOOKS: Focus on "Fear of Privacy Leaks" or "Shadow AI" dangers. Start with a "Result-First" statement.
- ANALOGIES: Use sharp analogies to explain complex breakthroughs.
- 3x ARTICLE EVIDENCE: You MUST explicitly reference source articles, documentation, or code repositories at least 3 times during the script to build authority.
- CTAs: At the end of every script, you MUST first ask a highly provocative, open-ended question to the viewers about the topic to drive comments. THEN, immediately after the question, you MUST explicitly say verbatim: "Follow me on Telegram for more AI news just like this! Link is on my channel home page. And subscribe for daily AI updates." This is a hard requirement for the outro. """

RESEARCH_AGENT_TEMPLATE = """{persona}

RESEARCH AGENT TASK:
Review the following technical news and search context.
Extract the raw facts, announcements, tweets, controversies, and implications.
Do NOT write a script. Just extract the core narrative elements.

NEWS CONTEXT:
{news_context}

Return ONLY a JSON object:
{{
  "facts": ["Fact 1", "Fact 2"],
  "controversies": ["Controversy 1"],
  "implications": ["Implication 1"],
  "core_narrative": "A one paragraph summary of the raw narrative"
}}"""

HOOK_AGENT_TEMPLATE = """{persona}

HOOK AGENT TASK:
Based on the following research, generate 10 potential YouTube Shorts hooks (<1.5s).
Hooks MUST create surprise, contradiction, urgency, or curiosity. No greetings. No generic statements.

RESEARCH:
{research_json}

Return ONLY a JSON object:
{{
  "hooks": [
    {{
      "text": "Hook text",
      "curiosity_score": 1-10,
      "emotional_trigger_score": 1-10,
      "reason": "Why it works"
    }}
  ]
}}"""

NARRATIVE_AGENT_TEMPLATE = """{persona}

NARRATIVE AGENT TASK:
Using the selected hook and research, create a short storytelling flow and escalating structure.
Include:
1. Hook (The selected hook)
2. Context (3-10s) - Who, What, Why it matters quickly.
3. Escalation (10-25s) - Implications, consequences, future impact. Include ARTICLE EVIDENCE #1 here.
4. The Analogy (25-35s) - Use a high-impact analogy to simplify a complex point. Include ARTICLE EVIDENCE #2 here.
5. The Twist (35-42s) - A counter-intuitive technical fact. Include ARTICLE EVIDENCE #3 here.
6. Personal Stakes (42-50s) - Explicitly state how this affects the viewer's job, wallet, or daily life. Use "YOU" and "YOUR".
7. Open Loop (50-56s) - Lingering provocative thought to drive engagement.
8. CTA (Last 4s) - Sequential Telegram promotion.

RESEARCH:
{research_json}

SELECTED HOOK:
{selected_hook}

{selection_instruction}

Return ONLY a JSON object representing the narrative draft (not the final schema yet, just the content parts):
{{
  "hook": "...",
  "context": "...",
  "escalation": "...",
  "insight": "...",
  "personal_stakes": "...",
  "open_loop": "..."
}}"""

RETENTION_OPTIMIZER_TEMPLATE = """{persona}

RETENTION OPTIMIZER TASK:
Rewrite the narrative draft to remove fluff, shorten sentences, add pacing breaks, and increase curiosity density.
Fast sentence pacing. No filler. The viewer must keep watching because the script continuously creates unanswered questions (tension-release).

CRITICAL PAGING: 
- Add an ellipsis '...' after every technical term with 3+ syllables (e.g. 'Distributed... systems', 'Architecture...'). 
- This forces the TTS to pause so viewers can process the complexity.

NARRATIVE DRAFT:
{narrative_json}

Return ONLY a JSON object:
{{
  "optimized_script": "The full rewritten text combining all parts into a fast-paced script."
}}"""

# ── PHASE 2: RETENTION SCIENTIST AGENT ────────────────────────────────────────
RETENTION_SCIENTIST_TEMPLATE = """{persona}

RETENTION SCIENTIST TASK:
Analyze the optimized script and inject PROVEN retention patterns at calculated intervals.
You are a YouTube Shorts retention strategist. Your ONLY job is to maximize the percentage of viewers who watch to the end.

CRITICAL RETENTION RULES (based on 2026 YouTube Shorts algorithm data):
1. HOOK DENSITY: The first 1.5 seconds (first 6 words) MUST contain a surprising claim, stat, or contradiction.
   - BAD: "Today we're going to talk about AI."
   - GOOD: "OpenAI just deleted their safety team."

2. OPEN LOOPS: Plant at least 3 "open loops" (unanswered questions) in the first 20 seconds.
   - Technique: Mention something intriguing but don't resolve it for 8-12 seconds.
   - Example: "But here's the part nobody is talking about..." then continue with OTHER info before resolving.

3. PATTERN INTERRUPTS: Every 8-12 seconds, inject a cognitive shift:
   - Rhetorical question ("But wait...")
   - Contradiction ("The crazy part?")
   - Number/stat bomb ("$4.2 billion.")
   - Direct address ("Here's why YOU should care.")
   - Emotional pivot ("And that's when everything changed.")

4. CURIOSITY GAPS: End every major point with an incomplete thought that requires the next sentence to resolve.
   - BAD: "The model scored 95% on the benchmark. It was impressive."
   - GOOD: "The model scored 95%. But that's not the scary part..."

5. PAYOFF STACKING: The most valuable, surprising, or controversial information MUST be in the LAST 15 seconds.
   Viewers who reach 70% completion almost always finish. Front-load curiosity, back-load payoff.

6. VOCAL VARIETY MARKERS: Add explicit markers for TTS energy:
   - ALL CAPS for emphasis words (max 2 per sentence)
   - "..." for dramatic pauses (1-2 per 15 seconds)
   - Short sentences (< 8 words) after complex explanations
   - "!" for energy spikes at key reveals

SCRIPT TO ENHANCE:
{optimized_script}

Return ONLY a JSON object:
{{
  "retention_enhanced_script": "The full rewritten script with all retention patterns injected",
  "retention_map": {{
    "open_loops": [
      {{"text": "The phrase that opens the loop", "planted_at_word": 15, "resolved_at_word": 45}}
    ],
    "pattern_interrupts": [
      {{"type": "contradiction", "text": "But here's the twist...", "at_word": 30}}
    ],
    "curiosity_gap_ratio": 0.65,
    "hook_word_count": 6,
    "payoff_zone_start_word": 120,
    "retention_risk_zones": [
      {{"at_word": 50, "risk": "explanation_fatigue", "mitigation": "Added rhetorical question"}}
    ]
  }}
}}"""

SELECTOR_AGENT_TEMPLATE = """{persona}

SELECTOR AGENT TASK:
Analyze the following tech news context and pick the SINGLE most impactful, surprising, and high-retention AI/Tech story for a 60-second video.

CRITICAL AVOIDANCE RULE:
You MUST NOT select any story that is semantically similar to the 'RECENTLY COVERED STORIES' listed in the context. If the hottest trending story matches a recently covered one, SKIP IT and pick the next best unique story.

{selection_instruction}

NEWS CONTEXT:
{news_context}

Return ONLY a JSON object:
{{
  "selected_headline": "The exact headline or title",
  "selected_url": "The exact URL",
  "reason": "Briefly why this was picked (focus on viral potential and uniqueness)"
}}"""

HUMANIZER_AGENT_TEMPLATE = """{persona}

HUMANIZER AGENT TASK:
This is the final step. Fix robotic phrasing, repetitive AI wording, over-explanation, and "In conclusion" style endings.
Add contractions, punchier cadence, and conversational flow.
Format the output EXACTLY matching the required schema below.

OPTIMIZED SCRIPT:
{optimized_script}

SCHEMA REQUIREMENTS:
{schema_requirements}

CRITICAL SUBTITLE RULE: The `subtitle_chunks` array MUST break the script down into extremely small chunks of EXACTLY 1 to 3 words maximum. Do not generate long sentences for subtitles.

Return ONLY the final JSON object matching the schema. No markdown wrapping unless inside the string values. No explanations."""

FACT_EXTRACTOR_TEMPLATE = """{persona}

TASK: Extract ONLY the technical facts, data points, and narrative details for the specific story requested below. 
IGNORE all other news stories or search results present in the context. Focus on providing the 'isolated truth' for this one story.

TARGET STORY: {target_headline}

CONTEXT:
{context}

Return ONLY a JSON object:
{{
  "facts": ["Fact 1", "Fact 2"],
  "controversies": ["Controversy 1"],
  "implications": ["Implication 1"],
  "core_narrative": "A one paragraph summary focusing ONLY on this story."
}}"""

def get_hottest_tech_topic(client, avoid_list=""):
    """Uses Gemini Search grounding to find today's single most VIRAL AI news story from Google Trends."""
    print("🔥 Fetching hottest AI tech topic for today (Google Trends Analysis)...")
    
    avoid_prompt = f"\n\nCRITICAL: DO NOT pick any topics related to the following recently covered stories:\n{avoid_list}" if avoid_list else ""
    
    attempts = 0
    while attempts < 3:
        try:
            response = client.models.generate_content(
                model='gemini-2.5-flash',
                contents=(
                    "Analyze today's Google Trends and viral tech news. "
                    "What is the single most trending AI search topic, breakout term, or breaking news story in the last 24 hours? "
                    "Look for: high search volume spikes on Google Trends related to AI, LLMs, or new model launches. "
                    f"{avoid_prompt}\n\n"
                    "Return ONLY a JSON object with two fields: "
                    "'topic' (3-6 word phrase, e.g. 'Google Gemini 1.5 Pro breakout trend') and "
                    "'keywords' (list of 6-8 specific Google Trends search keywords). No markdown, no explanation."
                ),
                config=types.GenerateContentConfig(
                    tools=[{'google_search': {}}]
                )
            )
            raw = response.text.strip()
            # Robust extraction: find the first { and last }
            if "{" in raw and "}" in raw:
                raw = raw[raw.find("{"):raw.rfind("}")+1]
            
            data = json.loads(raw)
            print(f"📈 Google Trends Hot Topic: {data['topic']}")
            return data
        except Exception as e:
            err_str = str(e).upper()
            if "429" in err_str or "RESOURCE_EXHAUSTED" in err_str:
                wait = (attempts + 1) * 5
                print(f"⚠️ Google Trends rate limited (429). Retrying in {wait}s... (Attempt {attempts+1}/3)")
                time.sleep(wait)
                attempts += 1
                continue
            print(f"⚠️ Could not fetch Google Trends topic: {e}. Proceeding with RSS only.")
            return None
    
    print("⚠️ Google Trends exhausted after retries. Proceeding with RSS only.")
    return None

def pick_and_generate_script(articles=None, extra_instruction="", forced_article=None, topic_type="research", failed_topics=[]):
    client = genai.Client(api_key=GEMINI_API_KEY)
    
    day_name, slot, category = get_slot_info()
    strategy_enhancement = get_category_prompt_enhancement(category, slot)
    
    # ── STEP -2: REPETITION AVOIDANCE (Moved Up) ────────────────────────────────────────
    tracker = load_tracker()
    recent_history = tracker.get("history", [])[-15:]
    # Also include titles from the last 7 days list for better coverage
    recent_titles = tracker.get("used_titles", [])[-30:]
    
    avoid_items = [h.get('news_headline', h.get('title')) for h in recent_history] + recent_titles
    if failed_topics:
        avoid_items += failed_topics
        
    combined_avoid = list(set(avoid_items))
    
    avoid_list_str = "\n".join([f"- {t}" for t in combined_avoid if t])
    avoid_instruction = f"CRITICAL: RECENTLY COVERED STORIES (DO NOT REPEAT THESE TOPICS):\n{avoid_list_str}\n\n" if avoid_list_str else ""

    # ── STEP -1.5: FETCH HOTTEST TOPIC ──────────────────────────────────────────
    # Pass the avoid list to Google Trends fetcher
    hot_topic = get_hottest_tech_topic(client, avoid_list=avoid_list_str)
    hot_keywords = [kw.lower() for kw in hot_topic.get("keywords", [])] if hot_topic else []
    hot_topic_str = hot_topic.get("topic", "") if hot_topic else ""

    news_context = avoid_instruction
    if forced_article:
        print(f"🎯 STEP -1: Using Forced Topic -> {forced_article}")
        news_context += f"FORCED TOPIC TO COVER:\n{forced_article}\n"
    else:
        # ── STEP 0: FETCH & FILTER + RE-RANK BY VIRAL POTENTIAL ───────────────────────
        if articles:
            print(f"📡 STEP 0: Scoring {len(articles)} articles for viral potential (engagement-weighted)...")
            
            # Fetch global trending articles from NewsAPI as an additional boost
            from fetch_research_papers import fetch_trending_from_newsapi
            trending_boost = fetch_trending_from_newsapi()
            articles += trending_boost
            
            seen_titles_in_this_batch = []
            filtered_articles = []
            
            for art in articles:
                title = art.get('title', '')
                url = art.get('url', '')
                
                # 1. Uniqueness check
                is_unique, _ = check_story_uniqueness(new_title=title, new_url=url)
                if not is_unique: continue
                
                # 2. Internal batch uniqueness
                from rapidfuzz import fuzz
                if any(fuzz.token_set_ratio(title.lower(), s.lower()) > 80 for s in seen_titles_in_this_batch):
                    continue
                    
                # ── 3. MULTI-SIGNAL VIRAL SCORING (Phase 1 Upgrade) ──────────
                title_lower = title.lower()
                
                # A. Keyword Score (legacy, reduced weight)
                keyword_score = sum(15 for kw in hot_keywords if kw in title_lower)
                breaking_keywords = ["launch", "release", "leak", "breakthrough", "benchmark", "announces", "unveils", "shuts down",
                                     "lawsuit", "ban", "hack", "scandal", "fired", "exposed", "shutdown", "raises", "billion", "million",
                                     "warns", "danger", "kills", "replaces", "outperforms", "beats", "surpass", "free", "open-source"]
                keyword_score += sum(10 for kw in breaking_keywords if kw in title_lower)
                controversy_keywords = ["wrong", "lie", "fake", "scam", "caught", "secretly", "hidden", "nobody", "shocking",
                                        "insane", "crazy", "terrifying", "scary", "devastating", "destroy", "war"]
                keyword_score += sum(12 for kw in controversy_keywords if kw in title_lower)
                big_names = ["google", "apple", "openai", "meta", "microsoft", "nvidia", "tesla", "amazon", "anthropic", "deepmind"]
                keyword_score += sum(8 for name in big_names if name in title_lower)
                
                # B. Source Engagement Score (NEW: from trending engine)
                engagement_score = art.get("_engagement_score", 0)  # Pre-computed by trending_engine
                if not engagement_score:
                    # Legacy sources without engagement data get base scores by type
                    if art.get("type") == "trending": engagement_score = 20
                    elif art.get("type") == "tools": engagement_score = 10
                    elif art.get("type") == "research": engagement_score = 10
                    else: engagement_score = 5
                
                # C. Trending Velocity Score (NEW: how fast is this topic rising?)
                trending_velocity_score = 0
                eng = art.get("_engagement", {})
                if art.get("type") == "reddit_trending":
                    velocity = eng.get("upvote_velocity", 0)
                    if velocity > 100: trending_velocity_score = 40
                    elif velocity > 50: trending_velocity_score = 30
                    elif velocity > 20: trending_velocity_score = 20
                    elif velocity > 5: trending_velocity_score = 10
                elif art.get("type") == "youtube_trending":
                    views = eng.get("views", 0)
                    if views > 100000: trending_velocity_score = 40
                    elif views > 50000: trending_velocity_score = 30
                    elif views > 10000: trending_velocity_score = 20
                elif art.get("type") == "github_trending":
                    spd = eng.get("stars_per_day", 0)
                    if spd > 100: trending_velocity_score = 35
                    elif spd > 50: trending_velocity_score = 25
                    elif spd > 10: trending_velocity_score = 15
                
                # D. Niche Gap Score (NEW: prefer topics competitors haven't covered)
                niche_score = 0
                niche_types = ["github_trending", "reddit_trending"]
                if art.get("type") in niche_types:
                    niche_score = 15  # Niche sources get a boost
                
                # E. Recency Score
                recency_score = 0
                pub_at = art.get("publishedAt", "")
                if pub_at:
                    try:
                        pub_dt = datetime.fromisoformat(pub_at.replace('Z', '+00:00'))
                        hours_ago = (datetime.now(timezone.utc) - pub_dt).total_seconds() / 3600
                        if hours_ago < 6: recency_score = 25
                        elif hours_ago < 12: recency_score = 20
                        elif hours_ago < 24: recency_score = 15
                        elif hours_ago < 48: recency_score = 8
                    except: pass
                
                # F. Type-Specific Scoring Boosts
                type_score = 0
                if topic_type == "tools":
                    tool_keywords = ["tool", "app", "ui", "workflow", "extension", "github", "build", "sdk", "library", "software", "try-on", "use case", "plugin"]
                    type_score += sum(15 for kw in tool_keywords if kw in title_lower)
                    if art.get("type") in ["tools", "github_trending"]:
                        type_score += 25
                elif topic_type == "news":
                    news_keywords = ["breaking", "lawsuit", "scandal", "fires", "ban", "partnership", "ceo", "acquires", "invests", "valuation", "trending", "revenue", "warns"]
                    type_score += sum(15 for kw in news_keywords if kw in title_lower)
                    if art.get("type") in ["trending", "youtube_trending"]:
                        type_score += 25
                elif topic_type == "research":
                    research_keywords = ["paper", "arxiv", "architecture", "researchers", "study", "dataset", "framework", "speculative decoding", "proof", "benchmark", "molecule", "polymerase"]
                    type_score += sum(15 for kw in research_keywords if kw in title_lower)
                    if art.get("type") in ["research", "reddit_trending"]:
                        type_score += 25
                
                # ── COMPOSITE VIRAL SCORE (weighted blend) ──
                hot_score = (
                    keyword_score * 0.15 +
                    engagement_score * 0.35 +
                    trending_velocity_score * 0.25 +
                    niche_score * 0.15 +
                    recency_score * 0.10 +
                    type_score * 0.10
                )

                art['_hot_score'] = round(hot_score, 1)
                art['_score_breakdown'] = {
                    'kw': keyword_score, 'eng': engagement_score, 
                    'vel': trending_velocity_score, 'niche': niche_score,
                    'rec': recency_score, 'type': type_score
                }
                filtered_articles.append(art)
                seen_titles_in_this_batch.append(title)
            
            if not filtered_articles:
                print("⚠️ No unique viral articles. Falling back to Search...")
                articles = None
            else:
                # Rank by composite viral score
                filtered_articles.sort(key=lambda x: x.get('_hot_score', 0), reverse=True)
                top = filtered_articles[0]
                bd = top.get('_score_breakdown', {})
                print(f"🏆 Top Viral Candidate: '{top.get('title')}' (Score: {top['_hot_score']:.1f})")
                print(f"   Breakdown: kw={bd.get('kw',0)} eng={bd.get('eng',0)} vel={bd.get('vel',0)} niche={bd.get('niche',0)} rec={bd.get('rec',0)} type={bd.get('type',0)}")
                articles = filtered_articles

        # ── STEP 1: GEMINI SEARCH FALLBACK (biased toward hot topic) ────────────
        if not articles:
            search_subject = hot_topic_str if hot_topic_str else f"{topic_type} about {category}"
            print(f"🔍 STEP 1: Using Gemini Search for '{search_subject}'...")
            search_query = (
                f"Latest breaking news and technical details about: {search_subject}. "
                f"Focus on announcements, benchmarks, or launches in the last 24 hours."
            )
            
            try:
                search_response = client.models.generate_content(
                    model='gemini-2.5-flash', # Use stable flash for tools
                    contents=search_query,
                    config=types.GenerateContentConfig(
                        tools=[{'google_search': {}}]
                    )
                )
                
                # Extract URLs from grounding metadata to ensure we have real links for screenshots
                grounding_links = []
                if search_response.candidates and search_response.candidates[0].grounding_metadata:
                    gm = search_response.candidates[0].grounding_metadata
                    if hasattr(gm, 'grounding_chunks'):
                        for chunk in gm.grounding_chunks:
                            if hasattr(chunk, 'web') and chunk.web.uri:
                                uri = chunk.web.uri
                                # Filter out common dead-ends, search redirects, or unsupported formats (PDF)
                                if any(x in uri.lower() for x in ["google.com/search", "bing.com/search", "search?", "click?", ".pdf"]):
                                    continue
                                grounding_links.append(f"{chunk.web.title}: {uri}")
                
                links_str = "\n".join(grounding_links)
                # Use the grounded response to build a context
                news_context += f"GEMINI SEARCH RESULTS (Grounded):\n{search_response.text}\n\nSOURCES FOUND:\n{links_str}\n"
                print(f"✅ Gemini Search completed with {len(grounding_links)} sources.")
            except Exception as e:
                print(f"⚠️ Gemini Search failed: {e}. Falling back to empty context.")
                news_context = "No news articles found."
        else:
            for idx, art in enumerate(articles[:20]):
                title = art.get('title', '')
                desc = art.get('description', '')
                source = art.get('source', {}).get('name', '')
                url = art.get('url', '')
                news_context += f"\n[{idx+1}] Title: {title}\nDescription: {desc}\nSource: {source}\nURL: {url}\n"

    # Build the story selection instruction
    if topic_type == "tools":
        content_desc = "latest trending AI tools, product workflows, and developer libraries/applications"
    elif topic_type == "news":
        content_desc = "latest breaking AI model launches, corporate tech updates, and industry announcements"
    else:
        content_desc = "trending AI research papers, model architectures, and deep engineering breakthroughs"

    from config import ENABLE_LONGFORM
    is_longform = ("Slot C" in slot) and ENABLE_LONGFORM
    
    if is_longform:
        selection_instruction = (
            f"Analyze the following {content_desc} and pick 1 MAIN story for a deep-dive, and 3-5 RAPID news updates.\n"
            "SELECTION FILTERS:\n"
            "1. MUST create a fast-paced 'News Roundup + Deep Dive' format (The Vaibhav Sisinty style).\n"
            "2. MUST be explainable in 120-180s of extremely high-energy, fast-paced speech (approx 350-450 words total).\n"
            "3. MUST contain a high-stakes Hook, a rapid-fire News Roundup (3-5 quick hits), and 1 Deep Dive Workflow.\n"
            "4. PRIORITIZE: Major industry shifts, model benchmarks, or extreme utility for the deep dive.\n"
            "5. VOCAL DYNAMICS: You MUST use heavy punctuation (commas, ellipses '...', exclamation marks, italics, ALL CAPS) around key technical terms and transitions. The TTS engine relies entirely on punctuation to vary pitch and emphasis. Never use plain unpunctuated sentences for important points.\n"
            "FORMAT: You MUST follow the strict 4-part structure: Hook -> News Roundup -> Deep Dive -> Outro.\n"
        )
        prompt_requirements = f"""Return ONLY this exact JSON (no markdown, no explanation):
{{
  "title_options": ["Title idea 1", "Title idea 2", "Title idea 3"],
  "description": "Full 100+ word rich SEO description for youtube describing the video, including timestamps and credits.",
  "use_case_evidence_url": "MANDATORY: A direct, valid URL from the 'SOURCES FOUND' section to be used as visual evidence.",
  "title": "Punchy YouTube title max 60 chars",
  "hook_script": "15-second high stakes intro (approx 30 words). Stark contrast, direct eye contact feel.",
  "news_roundup": "Rapid-fire coverage of 3-5 news updates. Use bold transitions like 'UPDATE 1...' (approx 150 words).",
  "deep_dive_tutorial": "A step-by-step breakdown or workflow of the main story/tool. Fast paced (approx 200 words).",
  "outro_cta": "Subscribe and comment prompt (approx 30 words).",
  "script": "The FULL unified voiceover script seamlessly concatenating hook_script, news_roundup, deep_dive_tutorial, and outro_cta into ONE single flowing text block. Target total word count: 350-450 words.",
  "hook_text": "The exact first 5-8 words of the script.",
  "relevant_links": ["https://github.com/...", "https://arxiv.org/abs/..."],
  "phonetic_pronunciation_map": {{"NVIDIA": "In-vid-yah"}},
  "hook": "Matches the first sentence of the script",
  "summary": "One line summary",
  "sub_category": "AI/Machine Learning",
  "breaking_news_level": 9,
  "retention_cues": [{{"timestamp": 3.0, "effect": "zoom_in", "reason": "hook_impact"}}],
  "subtitle_chunks": [{{
      "chunk_id": 1, "text": "Sentence 1", "start": 0.00, "end": 3.50, 
      "has_infographic": true, "infographic_type": "process|slide", 
      "infographic_data": {{"steps": ["Step 1", "Step 2"]}},
      "nano_visual_prompt": "A highly specific, cinematic visual description for THIS sentence. Must depict the exact subject/entity/concept spoken in this sentence. Example: 'Satellite view of Earth at night showing glowing city lights and data center hotspots, cinematic 9:16, dark background'. NO TEXT in the image. NO faces of real people. Photorealistic, 8K."
  }}],
  "original_news_headline": "Exact headline",
  "original_news_url": "Direct article URL",
  "keywords": ["AI"],
  "hashtags": ["#AI", "#CyberSecurity", "#DataPrivacy", "#TechNews"],
  "comment_hook": "Provocative question to drive engagement (e.g. 'Which department at your job is leaking the most data?')"
}}"""
    else:
        if topic_type == "tools":
            selection_instruction = (
                f"Analyze the following {content_desc} and pick the SINGLE most trending AI tool or hands-on product to teach the audience.\n"
                f"PRIMARY CATEGORY: AI Tools Teaching\n"
                "SELECTION FILTERS:\n"
                "1. PRIORITIZE: Tools with extremely high utility (e.g. Chrome extensions, devtools like Cursor, Claude Code, open-source libraries) that speed up work. Pick a tool that the viewer can actually start using today.\n"
                "2. VISUAL DEMONSTRATION REQUIRED: The final script and subtitle chunks MUST explicitly describe the visual interface and steps to use the tool. The `nano_visual_prompt` fields MUST describe highly specific, actual UI screenshots of this tool at each step.\n"
                "3. MUST be explainable in exactly <58s (approx 150-170 words total). Strict 60s limit.\n"
                "4. FORMAT: Hook (surprise/contradiction about a problem) -> Tool Walkthrough (Step-by-step teaching) -> Visual Proof -> Call to Action (Check the link/pinned comment)."
            )
            prompt_requirements = f"""Return ONLY this exact JSON (no markdown, no explanation):
{{
  "title_options": ["Title Case + Emoji + Curiosity Gap 1", "Title Case + Emoji + Curiosity Gap 2"],
  "description": "Full 100+ word rich SEO description for youtube describing the video, including timestamps and credits.",
  "use_case_evidence_url": "MANDATORY: A direct, valid URL from the 'SOURCES FOUND' section to be used as visual evidence.",
  "title": "Punchy YouTube title max 60 chars",
  "hook_script": "The Hook (<1.5s): Start with a Result-First statement about a massive problem. Approx 6 words.",
  "problem_context": "The Problem (3-10s): State why standard workflows are too slow or outdated. Approx 20 words.",
  "solution_tech": "The Solution (10-45s): Teach the exact steps/recipe to use this specific AI tool. Give concrete technical tips. Approx 80 words.",
  "retention_loop": "The Retention Loop (45-55s): Provide a seamless bridge back to the opening statement. Approx 15 words.",
  "outro_cta": "Call to Action: Try this tool now and follow on Telegram for daily devtools tips. Approx 10 words.",
  "script": "The FULL unified voiceover script seamlessly concatenating hook_script, problem_context, solution_tech, retention_loop, and outro_cta into ONE single flowing text block. Target total duration: 50-58 sec (approx 150-170 words). STRICT MAXIMUM: 58 seconds.",
  "hook_text": "The exact first 5-8 words of the script.",
  "relevant_links": ["https://github.com/...", "https://arxiv.org/abs/..."],
  "phonetic_pronunciation_map": {{"NVIDIA": "In-vid-yah"}},
  "hook": "Matches the first sentence of the script",
  "summary": "One line summary",
  "sub_category": "AI Tools",
  "breaking_news_level": 9,
  "retention_cues": [{{"timestamp": 3.0, "effect": "zoom_in", "reason": "hook_impact"}}],
  "subtitle_chunks": [{{
      "chunk_id": 1, "text": "Sentence 1", "start": 0.00, "end": 2.50,
      "nano_visual_prompt": "A highly specific, cinematic UI screenshot description for THIS sentence showing the actual tool interface. Example: 'UI screenshot of Cursor AI editor sidebar with chat panel showing active code generations, dark mode, 9:16 vertical'. NO TEXT in the image except the clean editor interface. Photorealistic, 8K."
  }}],
  "original_news_headline": "Exact headline",
  "original_news_url": "Direct article URL",
  "keywords": ["AI Tools", "Developer Tools", "Productivity"],
  "hashtags": ["#AITools", "#DevTools", "#Programming", "#Python", "#AI"],
  "comment_hook": "A custom question: 'What is your favorite new AI tool this week? Let me know below! 👇'"
}}"""
        elif topic_type == "news":
            selection_instruction = (
                f"Analyze the following {content_desc} and pick the SINGLE most shocking or viral tech news story.\n"
                f"PRIMARY CATEGORY: AI & Tech News\n"
                "SELECTION FILTERS:\n"
                "1. PRIORITIZE: High-stakes industry announcements, CEO updates, scandals, major business revenue shifts, or model benchmark leaks. Stories with strong drama or massive consequences go viral.\n"
                "2. EVIDENCE REQUIRED: You MUST cite specific article evidence, numbers, dates, or direct quotes at least 3 times in the script. The `use_case_evidence_url` field is MANDATORY and must be the news article URL.\n"
                "3. MUST be explainable in exactly <58s (approx 150-170 words total). Strict 60s limit.\n"
                "4. FORMAT: Hook (Breaking news hook) -> Context (The announcement/event) -> Evidence & Deconstruction -> Personal Stakes -> Outro Discussion (Provocative question)."
            )
            prompt_requirements = f"""Return ONLY this exact JSON (no markdown, no explanation):
{{
  "title_options": ["Title Case + Emoji + Curiosity Gap 1", "Title Case + Emoji + Curiosity Gap 2"],
  "description": "Full 100+ word rich SEO description for youtube describing the video, including timestamps and credits.",
  "use_case_evidence_url": "MANDATORY: A direct, valid URL from the 'SOURCES FOUND' section to be used as visual evidence.",
  "title": "Punchy YouTube title max 60 chars",
  "hook_script": "The Hook (<1.5s): Start with a dramatic Result-First breaking news hook. Approx 6 words.",
  "problem_context": "The Problem (3-10s): State why this news changes everything or presents a massive controversy. Approx 20 words.",
  "solution_tech": "The Solution (10-45s): Explain the tech news details, citing article evidence, quotes, and stats. Approx 80 words.",
  "retention_loop": "The Retention Loop (45-55s): Seamlessly bridge back to the opening statement. Approx 15 words.",
  "outro_cta": "Call to Action: Drop your thoughts in the comments and follow on Telegram for breaking AI news. Approx 10 words.",
  "script": "The FULL unified voiceover script seamlessly concatenating hook_script, problem_context, solution_tech, retention_loop, and outro_cta into ONE single flowing text block. Target total duration: 50-58 sec (approx 150-170 words). STRICT MAXIMUM: 58 seconds.",
  "hook_text": "The exact first 5-8 words of the script.",
  "relevant_links": ["https://github.com/...", "https://arxiv.org/abs/..."],
  "phonetic_pronunciation_map": {{"NVIDIA": "In-vid-yah"}},
  "hook": "Matches the first sentence of the script",
  "summary": "One line summary",
  "sub_category": "AI News",
  "breaking_news_level": 9,
  "retention_cues": [{{"timestamp": 3.0, "effect": "zoom_in", "reason": "hook_impact"}}],
  "subtitle_chunks": [{{
      "chunk_id": 1, "text": "Sentence 1", "start": 0.00, "end": 2.50,
      "nano_visual_prompt": "A highly specific, cinematic visual representing the tech news article or company logo. Example: 'A tech news website article screenshot showing a header block about OpenAI, clean composition, dark mode, 9:16 vertical'. NO TEXT except the clean corporate branding. Photorealistic, 8K."
  }}],
  "original_news_headline": "Exact headline",
  "original_news_url": "Direct article URL",
  "keywords": ["AI News", "Tech News", "Breaking News"],
  "hashtags": ["#AINews", "#TechNews", "#BreakingNews", "#Google", "#OpenAI"],
  "comment_hook": "A custom question: 'What is your take on this massive shift? Let me know below! 👇'"
}}"""
        else: # research
            selection_instruction = (
                f"Analyze the following {content_desc} and pick the SINGLE most groundbreaking research paper or engineering blog.\n"
                f"PRIMARY CATEGORY: AI Research Papers\n"
                "SELECTION FILTERS:\n"
                "1. PRIORITIZE: Breakthrough architectures, speculative decoding, local model optimization milestones, or causal reasoning improvements. Focus on solving existing LLM bottlenecks.\n"
                "2. ACADEMIC EVIDENCE REQUIRED: You MUST mention the paper's title or authors, and cite specific academic evidence (such as benchmark percentages, model parameter sizes, or repository features). The `use_case_evidence_url` must be the arXiv or project website URL.\n"
                "3. MUST be explainable in exactly <58s (approx 150-170 words total). Strict 60s limit.\n"
                "4. FORMAT: Hook (Surprising limitation of current LLMs) -> The Paper's Discovery -> The Analogy (Simplified explanation of the math/architecture) -> Performance Stats -> CTA (Check the repo)."
            )
            prompt_requirements = f"""Return ONLY this exact JSON (no markdown, no explanation):
{{
  "title_options": ["Title Case + Emoji + Curiosity Gap 1", "Title Case + Emoji + Curiosity Gap 2"],
  "description": "Full 100+ word rich SEO description for youtube describing the video, including timestamps and credits.",
  "use_case_evidence_url": "MANDATORY: A direct, valid URL from the 'SOURCES FOUND' section to be used as visual evidence.",
  "title": "Punchy YouTube title max 60 chars",
  "hook_script": "The Hook (<1.5s): Start with a surprising limitation or benchmark about current LLMs. Approx 6 words.",
  "problem_context": "The Problem (3-10s): State why standard models struggle with this specific math/logical bottleneck. Approx 20 words.",
  "solution_tech": "The Solution (10-45s): Explain the paper's core breakthrough using a sharp analogy. Mention authors/title and stats. Approx 80 words.",
  "retention_loop": "The Retention Loop (45-55s): Seamlessly bridge back to the opening statement. Approx 15 words.",
  "outro_cta": "Call to Action: Read the full paper and follow on Telegram for daily AI research deconstructions. Approx 10 words.",
  "script": "The FULL unified voiceover script seamlessly concatenating hook_script, problem_context, solution_tech, retention_loop, and outro_cta into ONE single flowing text block. Target total duration: 50-58 sec (approx 150-170 words). STRICT MAXIMUM: 58 seconds.",
  "hook_text": "The exact first 5-8 words of the script.",
  "relevant_links": ["https://github.com/...", "https://arxiv.org/abs/..."],
  "phonetic_pronunciation_map": {{"NVIDIA": "In-vid-yah"}},
  "hook": "Matches the first sentence of the script",
  "summary": "One line summary",
  "sub_category": "AI Research",
  "breaking_news_level": 9,
  "retention_cues": [{{"timestamp": 3.0, "effect": "zoom_in", "reason": "hook_impact"}}],
  "subtitle_chunks": [{{
      "chunk_id": 1, "text": "Sentence 1", "start": 0.00, "end": 2.50,
      "nano_visual_prompt": "A highly specific, cinematic visual representing the academic paper structure or neural network architecture. Example: 'A clean mathematical diagram of neural connections or code blocks on a dark screen, futuristic 9:16 vertical'. NO TEXT except the clean diagram structures. Photorealistic, 8K."
  }}],
  "original_news_headline": "Exact headline",
  "original_news_url": "Direct article URL",
  "keywords": ["AI Research", "Machine Learning", "Neural Networks"],
  "hashtags": ["#AI", "#MachineLearning", "#DeepLearning", "#Research", "#Coding"],
  "comment_hook": "A custom question: 'What do you think of this mathematical approach? Let's discuss below! 👇'"
}}"""

    # Inject any extra instructions (e.g. screenshot avoidance, length adjustments) into context
    if extra_instruction:
        news_context += f"\n\nADDITIONAL INSTRUCTIONS:\n{extra_instruction}\n"

    engine = MultiAgentGenerationEngine(client, news_context, slot, category, strategy_enhancement, is_longform, raw_articles=articles)
    script_data = engine.execute(selection_instruction, prompt_requirements)
    
    if script_data:
        # Perform uniqueness check (Final safeguard)
        headline = script_data.get("original_news_headline", "")
        news_url = script_data.get("original_news_url", "")
        keywords = script_data.get("keywords", [])
        title = script_data.get("title", "")
        
        is_unique, msg = check_story_uniqueness(title, headline, keywords, news_url)
        if not is_unique:
            print(f"⚠️ [LOOP] Safeguard: Post-loop uniqueness check failed: {msg}")
            if headline:
                failed_topics.append(headline)
            if news_url:
                failed_topics.append(news_url)
            return None
            
    return script_data

class MultiAgentGenerationEngine:
    def __init__(self, client, context, slot, category, strategy_enhancement, is_longform, raw_articles=None):
        self.client = client
        self.context = context
        self.slot = slot
        self.category = category
        self.strategy_enhancement = strategy_enhancement
        self.is_longform = is_longform
        self.raw_articles = raw_articles

    def _call_gemini(self, prompt, model='gemini-2.5-flash'):
        attempts = 0
        current_model = model
        while attempts < 5:
            try:
                response = self.client.models.generate_content(
                    model=current_model,
                    contents=prompt,
                    config=types.GenerateContentConfig(
                        temperature=0.8,
                        response_mime_type='application/json'
                    )
                )
                raw = response.text.strip()
                if "{" in raw and "}" in raw:
                    raw = raw[raw.find("{"):raw.rfind("}")+1]
                
                return json.loads(raw)
            except Exception as e:
                err_str = str(e).upper()
                # Handle Overloaded (503), Resource Exhausted (429), or Model Deprecated (404)
                if any(x in err_str for x in ["503", "UNAVAILABLE", "RESOURCE_EXHAUSTED", "429", "NOT_FOUND", "404"]):
                    wait_time = (5 ** (attempts + 1)) + random.uniform(2, 5) # Progressive wait: 7s, 27s, 127s...
                    
                    # Model Fallback Logic
                    if current_model == 'gemini-2.5-pro':
                        print(f"⚠️ [LOOP] Model {current_model} is UNAVAILABLE. Falling back to gemini-2.5-flash...")
                        current_model = 'gemini-2.5-flash'
                        continue
                    elif current_model == 'gemini-2.5-flash' and attempts >= 1:
                        print(f"⚠️ [LOOP] Model {current_model} is OVERLOADED. Falling back to gemini-2.5-flash-lite...")
                        current_model = 'gemini-2.5-flash-lite'
                        continue
                        
                    print(f"⚠️ [LOOP] Call failed ({current_model}): Rate Limit/Overload. Retrying in {wait_time:.1f}s...")
                    time.sleep(wait_time)
                else:
                    print(f"⚠️ [LOOP] Call failed ({current_model}): {e}. Retrying...")
                    time.sleep(3)
                attempts += 1
        return None

    def execute(self, selection_instruction, prompt_requirements):
        print("🎯 [AGENT 0] Selector Agent: Picking the single best story...")
        selector_prompt = SELECTOR_AGENT_TEMPLATE.format(
            persona=SYSTEM_PERSONA,
            selection_instruction=selection_instruction,
            news_context=self.context
        )
        selection = self._call_gemini(selector_prompt)
        if not selection or "selected_headline" not in selection:
            print("⚠️ Selector Agent failed. Using raw context fallback.")
            # If we have articles, pick the top one from raw_articles as fallback
            if self.raw_articles and len(self.raw_articles) > 0:
                top = self.raw_articles[0]
                selected_headline = top.get("title", "AI Tech Breakthrough")
                selected_url = top.get("url", "")
                print(f"🔄 Fallback to Top Scored Article: {selected_headline}")
            else:
                selected_headline = "AI Tech Breakthrough"
                selected_url = ""
            selected_context = f"SELECTED STORY: {selected_headline}\nSOURCE: {selected_url}\n\nORIGINAL CONTEXT:\n{self.context}"
        else:
            selected_headline = selection["selected_headline"]
            selected_url = selection["selected_url"]
            
            # ── CONTEXT ISOLATION (Fixes topic-screenshot mismatch) ───────────
            isolated_context = ""
            if self.raw_articles:
                # Find matching article in the original list to provide rich but isolated context
                for art in self.raw_articles:
                    if art.get("url") == selected_url or art.get("title") == selected_headline:
                        isolated_context = (
                            f"Title: {art.get('title')}\n"
                            f"Description: {art.get('description')}\n"
                            f"Source: {art.get('source', {}).get('name')}\n"
                            f"URL: {art.get('url')}"
                        )
                        break
            
            if not isolated_context:
                # Fallback if no match found (e.g. search fallback)
                isolated_context = f"STORY: {selected_headline}\nSOURCE: {selected_url}"
                if "GEMINI SEARCH RESULTS" in self.context:
                    # If in search mode, we must include the grounded text but we'll instruct the agent to focus.
                    isolated_context += f"\n\nSEARCH CONTEXT:\n{self.context}"
            
            # ── CONTEXT SHARPENING (NEW) ──────────────────────────────────────
            # If we don't have rich RSS metadata, we MUST sharpen the search context
            # to prevent 'Hallucination Leakage' from other stories in the search result.
            print("🔬 [AGENT 0.5] Context Sharpener: Isolating target story facts...")
            sharpener_prompt = FACT_EXTRACTOR_TEMPLATE.format(
                persona=SYSTEM_PERSONA,
                target_headline=selected_headline,
                context=isolated_context # Pass the messy context to be sharpened
            )
            sharpened_data = self._call_gemini(sharpener_prompt)
            
            if sharpened_data and "core_narrative" in sharpened_data:
                isolated_context = (
                    f"STORY: {selected_headline}\n"
                    f"SOURCE: {selected_url}\n\n"
                    f"ISOLATED FACTS:\n{json.dumps(sharpened_data, indent=2)}"
                )
                print(f"✨ Context sharpened successfully for: {selected_headline}")
            else:
                print("⚠️ Context Sharpener failed. Falling back to raw isolation.")

            selected_context = (
                f"STRICT INSTRUCTION: You MUST ONLY research and write about the following story. "
                f"IGNORE all other news articles mentioned in any previous context.\n\n"
                f"TARGET STORY:\n{isolated_context}"
            )
            print(f"🔒 Isolated Context for downstream agents: {len(isolated_context)} chars")
            print(f"✅ Selected Story: {selected_headline}")

        print("🕵️ [AGENT 1] Research Agent: Extracting narrative elements...")
        research_prompt = RESEARCH_AGENT_TEMPLATE.format(
            persona=SYSTEM_PERSONA,
            news_context=selected_context
        )
        research = self._call_gemini(research_prompt)
        if not research: return None

        print("🪝 [AGENT 2] Hook Agent: Generating high-retention hooks...")
        hook_prompt = HOOK_AGENT_TEMPLATE.format(
            persona=SYSTEM_PERSONA,
            research_json=json.dumps(research)
        )
        hooks_data = self._call_gemini(hook_prompt)
        if not hooks_data or "hooks" not in hooks_data: return None
        
        # Pick best hook (highest combined score including swipe-stop power)
        best_hook = max(hooks_data["hooks"], key=lambda h: (
            h.get("curiosity_score", 0) + 
            h.get("emotional_trigger_score", 0) + 
            h.get("swipe_stop_score", h.get("curiosity_score", 0))  # Backward-compatible
        ))
        hook_text = best_hook.get('text', '')
        hook_words = len(hook_text.split())
        print(f"🎯 Selected Hook ({hook_words} words): {hook_text}")

        print("📖 [AGENT 3] Narrative Agent: Building escalating structure...")
        narrative_prompt = NARRATIVE_AGENT_TEMPLATE.format(
            persona=SYSTEM_PERSONA,
            research_json=json.dumps(research),
            selected_hook=hook_text,
            selection_instruction=selection_instruction
        )
        narrative = self._call_gemini(narrative_prompt, model='gemini-2.5-pro')
        if not narrative: return None

        print("⚡ [AGENT 4] Retention Optimizer: Maximizing pacing and curiosity density...")
        retention_prompt = RETENTION_OPTIMIZER_TEMPLATE.format(
            persona=SYSTEM_PERSONA,
            narrative_json=json.dumps(narrative)
        )
        optimized = self._call_gemini(retention_prompt, model='gemini-2.5-pro')
        if not optimized: return None

        # ── PHASE 2: RETENTION SCIENTIST (Agent 4.5) ──────────────────────────
        print("🧬 [AGENT 4.5] Retention Scientist: Injecting proven retention patterns...")
        retention_sci_prompt = RETENTION_SCIENTIST_TEMPLATE.format(
            persona=SYSTEM_PERSONA,
            optimized_script=optimized.get("optimized_script", "")
        )
        retention_result = self._call_gemini(retention_sci_prompt, model='gemini-2.5-pro')
        
        retention_map = {}
        if retention_result and "retention_enhanced_script" in retention_result:
            optimized["optimized_script"] = retention_result["retention_enhanced_script"]
            retention_map = retention_result.get("retention_map", {})
            cgr = retention_map.get("curiosity_gap_ratio", 0)
            loops = len(retention_map.get("open_loops", []))
            interrupts = len(retention_map.get("pattern_interrupts", []))
            print(f"   ✅ Retention: {loops} open loops, {interrupts} pattern interrupts, {cgr:.0%} curiosity gap ratio")
        else:
            print("   ⚠️ Retention Scientist failed (non-fatal). Using optimizer output directly.")

        print("🗣️ [AGENT 5] Humanizer Agent: Fixing AI cadence and returning final schema...")
        # Inject the selected headline and URL back into the requirements if they are missing
        refined_requirements = prompt_requirements
        if "original_news_headline" in refined_requirements:
            refined_requirements = refined_requirements.replace('"original_news_headline": "Exact headline"', f'"original_news_headline": "{selected_headline}"')
        if "original_news_url" in refined_requirements:
            refined_requirements = refined_requirements.replace('"original_news_url": "Direct article URL"', f'"original_news_url": "{selected_url}"')

        humanizer_prompt = HUMANIZER_AGENT_TEMPLATE.format(
            persona=SYSTEM_PERSONA,
            optimized_script=optimized.get("optimized_script", ""),
            schema_requirements=refined_requirements
        )
        final_script = self._call_gemini(humanizer_prompt, model='gemini-2.5-pro')
        
        if final_script:
            # Final safety check: ensure the headline/url are set correctly in the final object
            if not final_script.get("original_news_headline") or final_script.get("original_news_headline") == "Exact headline":
                final_script["original_news_headline"] = selected_headline
            if not final_script.get("original_news_url") or final_script.get("original_news_url") == "Direct article URL":
                final_script["original_news_url"] = selected_url
            
            # ── PHASE 2: Attach retention_map to the final script for downstream use ──
            if retention_map:
                final_script["retention_map"] = retention_map
            
            print("⭐ [PIPELINE] Multi-Agent script generation completed successfully.")
        return final_script
